### ISSUE TITLE
Webauthn security key results in Can't recover login challenge

### ISSUE THREAD

**Issue by assid2** [dani-garcia/vaultwarden#1840]
### Subject of the issue

Webauthn does not work
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.22.1
* Web-vault version: v2.20.4b
* Running within Docker: true
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: PostgreSQL
* Database version: PostgreSQL 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, ADMIN_TOKEN, YUBICO_CLIENT_ID, YUBICO_SECRET_KEY, SMTP_HOST, SMTP_SSL, SMTP_PORT, SMTP_FROM, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "**********://***********:************@***.**.***.**:****/***********",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*****.*****.***",
  "domain_origin": "*****://*****.*****.***",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "VaultWarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/bitwarden.log",
  "log_level": "warn",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": null,
  "org_creation_users": "******@*****.***,*********@*****.***",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "*********@*****.***",
  "smtp_from_name": "Bitwarden",
  "smtp_host": "****.*****.***",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "*********@*****.***",
  "templates_folder": "data/templates",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": "56265",
  "yubico_secret_key": "***",
  "yubico_server": null
}
```
</details>

* Other relevant details:

### Steps to reproduce

Use a registered yubikey to login to your account, 

### Expected behaviour

Authentication module should verify the key

### Actual behaviour

Received error : Can't recover login challenge

### Troubleshooting data

[2021-07-06 04:43:55.913][error][ERROR] 2FA token not provided
[2021-07-06 04:44:05.146][error][ERROR] Webauthn.
[CAUSE] UserNotVerified
[2021-07-06 04:44:07.259][vaultwarden::api::core::two_factor::webauthn][ERROR] Can't recover login challenge

**Comment by BlackDex** [comment]
I think i know where the issue is.
https://github.com/dani-garcia/vaultwarden/blob/3968bc8016611cdf9a84db68990f27624ab17889/src/db/models/two_factor.rs#L200

The only thing i do not know is what will happen if we set that to true and what implication it could have.
Does the token you use has any special User Verification capabilities?

@dani-garcia do you know if we can just change that value to true without any issues?

**Comment by dani-garcia** [comment]
Setting that value to true will enforce that the client is setting the user_verified flag when authenticating, setting it to false would disable the check instead, so if anything, using false would be the more compatible option.

This is where the check is being done, the only thing I can think of is that the client is setting the UserVerificationPolicy to required but not setting the user_verified flag?
https://github.com/kanidm/webauthn-rs/blob/02a99f534127b30c6f4df7f2d42bc24f76dc4211/src/core.rs#L635-L652

It would help to know which security key and which browser or client is causing the problem.

**Comment by sehraf** [comment]
> It would help to know which security key and which browser or client is causing the problem.

NitroKey FIDO2 + Chrome WebUI
NitroKey FIDO2 + Chrome Browser Extension
YubiKey 4 + Chrome WebUI

Both don't work anymore

**Comment by assid2** [comment]
I tried this on Yubikey 5NFC on both Firefox and Chrome.

**Comment by techsolo12** [comment]
I have this error with Yubikey 5C and 5 NFC on Firefox Desktop and Firefox and Chrome mobile Android.

**Comment by mr-kek** [comment]
Having the same issue.
Yubikey 5 HFC, Yubikey 5c NFC, Yubikey 5Ci NFC.
I'm on macOS using Safari.
Also tried with Chrome, same problem.

1st login, just says Error, WebAuthn, second login attempt give Error, Can't recover login challenge.

I can confirm that using touch id on safari to log in works, which is nice.

I can use the Yubikey's with the normal Yubikey OTP, but really want WebAuthn working. It hasn't worked for me at all with any version. I just upgraded to the latest vault warden, and I can't remember the error I got before, but now I get the same error as the OP.

**Comment by nick-stocks** [comment]
+1 I have this issue on Safari and Chrome with Solokey. TouchID does indeed work, though if you delete and recreate TouchID you have to give it a different name in Vaultwarden. Reusing breaks it.

FaceID also works if you log into the web on the iPhone, which is cool.

**Comment by BlackDex** [comment]
@assid2, have you tried yet to name the keys something with some gibberish name? And see if that solves it?

**Comment by coalfield** [comment]
+1 same issue with a similar synology docker setup, they key itself adds in fine but when logging in it fails.  Using Yubikey Nano 5

`[vaultwarden::api::core::two_factor::webauthn][ERROR] Can't recover login challenge`

**Comment by coalfield** [comment]
So after playing around with some of the config, this is miraculously is now working.  At first I removed all the WebAuth keys, then added a gibberish name as @BlackDex suggested, and it worked.  Then removed again and called it Nano 5 and that's also now working.  Not sure if its linked or fluke.  Of note I am still getting this (and only this) on the log:

`[error][ERROR] 2FA token not provided`

**Comment by BlackDex** [comment]
Ok, good to know. It could be that there is something within the cache which is causing this somehow. Not sure. But @assid2, if you could test this too that would be great.

@coalfield that message is normal during first login if I'm correct.
Nothing to worry about.

**Comment by mr-kek** [comment]
I tried gibberish, and same problem for me. Still doesn't work

**Comment by coalfield** [comment]
> I tried gibberish, and same problem for me. Still doesn't work

Does it pop up and ask for a pin even?  As mine was not doing that when it was not working.  Are you running on Synology by chance?  If so can try to remember the changes I made prior to it fixing itself on config

**Comment by mr-kek** [comment]
> > I tried gibberish, and same problem for me. Still doesn't work
> 
> Does it pop up and ask for a pin even? As mine was not doing that when it was not working. Are you running on Synology by chance? If so can try to remember the changes I made prior to it fixing itself on config

yes, running on a Synology, and yes it's asking for a pin every time.

**Comment by assid2** [comment]
Ok here is something I tried, (background info - i had reset my fido pin but shouldn't have any effect here)

1. I disabled all webauthn keys
2. re-registered 1 key, named   yubi keychain
3. I logged in with firefox (private browsing), during webauthn it asks for pin , it automatically accepts ONLY 4 characters and auto submits. [ this seems off  since pin codes can be longer than 4 characters ].
* Firefox does login now,  ( couldnt before since i had more than 4 character long pin ).
4. Tried to login with chrome (private browsing), this doesnt work.

**Comment by coalfield** [comment]
> @coalfield that message is normal during first login if I'm correct.

Good to know.  Not sure the reason for it... not liking seeing [error] in the logs :(

**Comment by szorlowski** [comment]
Ok guys. I've got a same issue and I couldn't solve that BUT for me the issue occurs only on windows. 
I've tried that on 3 machines with linux (mint20) and it worked well. 

I tried to disable antivirus and firewall but it didn't help. Maybe that info may help with solving the issue

**Comment by coalfield** [comment]
> Ok guys. I've got a same issue and I couldn't solve that BUT for me the issue occurs only on windows.
> I've tried that on 3 machines with linux (mint20) and it worked well.
> 
> I tried to disable antivirus and firewall but it didn't help. Maybe that info may help with solving the issue
> 
> EDIT: vaultwarden hosted on raspberry pi. Windows and linuxes were clients.
> 
> Summary: all logins on windows were blocked - web, desktop. On linux every login passed

So with mine the pi. Prompt never came up which is windows linked so it does make sense. Have a try removing and adding windows hello with the key. This means removing the pin code and re-adding it. This was definitely one of the things I did between getting the error and the error fixing itself

**Comment by szorlowski** [comment]
Unfortunately that ⬆️ didn't help but to be honest I was not hoping to. I found very interesting thing. I can log in on windows but with different machine. So there must be an issue with my home windows10 configuration or network config within it.

Still checking it and I will inform you guys when I found solution to it

**Comment by BlackDex** [comment]
With some help from @assid2, i think i have fixed this issue. See the linked PR.

**Comment by sehraf** [comment]
I still can't add my NitroKey again, getting the same webauthn error.
Is there anything more to do then updating to 1.22.2?

**Comment by BlackDex** [comment]
@sehraf could you enable debug logging and provide the logs from during the key registration and login attempt using that key?

**Comment by mr-kek** [comment]
Can confirm I'm all good now with the new version. Web Auth all working on macOS in safari with both yubikey and Touch ID.
Very happy. Thanks :)

**Comment by sehraf** [comment]
I found the error while collecting the logs:
> Jul 28 17:12:13 \<user\> vaultwarden[50946]: [2021-07-28 17:12:13.562][webauthn_rs::core][DEBUG] https://\<domain\> != https://\<domain\>/

Apparently i just had to remove the trailing `/` from my domain environment entry. Now it works!
