### ISSUE TITLE
New users can't accept organization invite

### ISSUE THREAD

**Issue by MariusVaice** [dani-garcia/vaultwarden#3424]
### Subject of the issue
New users can't join an organization with invites after Vaultwarden update.

### Deployment environment

* Vaultwarden version: v1.28.1
* Web-vault version: v2023.3.0b
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (CF-Connecting-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.39.2
* Clients used: web vault

### Steps to reproduce
From organization management invite a new user.
User registers via link in the email.
User logins for the first time. 

### Expected behaviour
After first user login, user should get a confirmation that organization admin should verify their account.

### Actual behaviour
After first login, user sees an error:
![image](https://user-images.githubusercontent.com/73332810/230431370-347a8d12-e60c-4ace-80b4-89f38e5b90f3.png)

### Troubleshooting data
Vaultwarden version 1.27.0 was working perfectly with the same configuration. No changes in configuration has been introduced.

**Comment by BlackDex** [comment]
I think you now have `Master Password Reset` enabled, and the old invites may cause issues with that.
Try to remove the user from the org and re-invite them, that should solve the issue.

**Comment by MariusVaice** [comment]
> I think you now have `Master Password Reset` enabled, and the old invites may cause issues with that. Try to remove the user from the org and re-invite them, that should solve the issue.

Unfortunately I've already tried to delete and invite the user again, but the problem persists. Also tried to invite with different user emails.

**Comment by BlackDex** [comment]
Do you have any logs of Vaultwarden?

**Comment by BlackDex** [comment]
You need to either check both checkboxes or only the first one.

If you have it like the image below, that will cause the issue.
![image](https://user-images.githubusercontent.com/610450/230444243-c164019e-6deb-4f84-88e5-c6b6dbd7cb29.png)

This probably needs to be addressed for future versions so it will ignore that specific setting, since the policy is not enabled.

**Comment by MariusVaice** [comment]
Yes, that was the issue.  Thanks for your fast response!

Just for future reference, in logs only one line is written:
[vaultwarden::api::core::organizations][ERROR] Reset password key is required, but not provided.
