### ISSUE TITLE
Vaultwarden no longer shows entries in the Webvault; Sync with Android app works

### ISSUE THREAD

**Issue by update-freak** [dani-garcia/vaultwarden#4949]
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.32.0
* Web-vault version: v2024.6.2b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.46.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, ADMIN_TOKEN, SMTP_HOST, SMTP_FROM, SMTP_FROM_NAME, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*****************************",
  "domain_origin": "*****://*****************************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": false,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Bitwarden_RS",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "******************",
  "smtp_from_name": "Bitwarden_RS",
  "smtp_host": "************",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "******************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Vaultwarden Build Version

v1.32.0

### Deployment method

Official Container Image

### Reverse Proxy

buildin in DSM

### Host/Server Operating System

NAS/SAN

### Operating System Version

Synology DSM 7.2

### Clients

Web Vault

### Client Version

v2024.6.2

### Steps To Reproduce

1. Login
2. You see the loading circle but no items

![vaultwarden](https://github.com/user-attachments/assets/1e30cf66-27df-44e4-a17d-a333a8a5bdc1)

### Expected Result

After a few seconds the items are shown

### Actual Result

The items are not shown after several minutes

### Logs

```text
[2024-09-13 16:07:57.520][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-09-13 16:07:57.528][request][INFO] GET /api/config
[2024-09-13 16:07:57.528][response][INFO] (config) GET /api/config => 200 OK
[2024-09-13 16:07:57.565][request][INFO] POST /identity/connect/token
[2024-09-13 16:07:57.565][request][INFO] GET /api/accounts/profile
[2024-09-13 16:07:57.568][response][INFO] (profile) GET /api/accounts/profile => 200 OK
[2024-09-13 16:07:57.573][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-09-13 16:07:57.575][request][INFO] GET /images/close-button.svg
[2024-09-13 16:07:57.575][response][INFO] (web_files) GET /<p..> [10] => 200 OK
[2024-09-13 16:07:57.581][request][INFO] GET /fonts/Open_Sans-normal-700.a39de6b1b80c7f21cf88.woff
[2024-09-13 16:07:57.581][response][INFO] (web_files) GET /<p..> [10] => 200 OK
[2024-09-13 16:07:57.587][request][INFO] GET /notifications/hub?access_token=geheim
[2024-09-13 16:07:57.587][vaultwarden::api::notifications::_][WARN] Request guard `WebSocket` is forwarding.
[2024-09-13 16:07:57.588][rocket::response::responder::_][WARN] Response was `None`.
[2024-09-13 16:07:57.588][rocket::server::_][WARN] Responding with registered (not_found) 404 catcher.
[2024-09-13 16:07:57.588][response][INFO] (web_files) GET /<p..> [10] => 404 Not Found
[2024-09-13 16:07:57.591][request][INFO] GET /api/sync?excludeDomains=true
[2024-09-13 16:07:57.613][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
[2024-09-13 16:07:57.658][request][INFO] GET /encrypt-worker.0d0845fabb9cc329f366.js
[2024-09-13 16:07:57.658][response][INFO] (web_files) GET /<p..> [10] => 200 OK
[2024-09-13 16:07:57.755][request][INFO] GET /44.b3b5a3a8f7626e22cead.js
[2024-09-13 16:07:57.805][response][INFO] (web_files) GET /<p..> [10] => 200 OK
[2024-09-13 16:08:28.398][request][INFO] POST /identity/connect/token
[2024-09-13 16:08:28.407][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-09-13 16:08:28.413][request][INFO] GET /api/sync
[2024-09-13 16:08:30.950][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
[2024-09-13 16:08:36.388][request][INFO] GET /alive
[2024-09-13 16:08:36.389][response][INFO] (alive) GET /alive => 200 OK
[2024-09-13 16:08:37.133][request][INFO] GET /icons/192.168.178.26/icon.png
[2024-09-13 16:08:37.389][response][INFO] (icon_internal) GET /icons/<domain>/icon.png => 200 OK
[2024-09-13 16:08:50.086][vaultwarden::api::core::accounts][DEBUG] Purging auth requests
[2024-09-13 16:08:50.085][vaultwarden::api::core::two_factor][DEBUG] Sending notifications for incomplete 2FA logins
```

### Additional Context

I also use AdGuard Home and Unbound on Synology NAS.
Reverse Proxy is used to direct to a domain like: https://vaultwarden.beispiel.dynv6.net
The Sync to Android App or Chrome Extension works successfully.

Docker compose (Passwords are modified)
version: "3.9"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    hostname: vaultwarden
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 1024
    security_opt:
      - no-new-privileges=true
    ports:
      - 1058:80
    volumes:
      - /volume1/docker/vaultwarden:/data:rw
    environment:
      - ADMIN_TOKEN=PASSWORT
      - DOMAIN=https://vaultwarden.beispiel.dynv6.net
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=geheim
      - SMTP_FROM=geheim
      - SMTP_FROM_NAME=Vaultwarden
      - SMTP_USERNAME=geheim
      - SMTP_PASSWORD=PASSWORT
    restart: always

**Comment by stefan0xC** [comment]
Can you check your web console what the browser says when this doesn't load? E.g. if there are blocked resources or exceptions thrown? If it's a blocked resource you might want to check your reverse proxy settings if you are overriding the content security policy. I mean this could potentially also be caused by browser extensions.

**Comment by update-freak** [comment]
With the developer tool I got 6 errors in Chrome:

WebSocketTransport.ts:81 WebSocket connection to ... failed

Error: Failed to start the connection: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

Unhandled Promise rejection: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled. ; Zone: <root> ; Task: null ; Value: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

zone.umd.js:1097 Unhandled Promise rejection: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled. ; Zone: <root> ; Task: null ; Value: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

Uncaught (in promise) TypeError: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.


Is it necessary to create WebSocket (as shown in Step 7 here: https://mariushosting.com/synology-install-vaultwarden-with-portainer/) ?

**Comment by stefan0xC** [comment]
That the websocket fails is a different issue. I am not familiar enough with Synology to know if the steps in the linked tutorial are correct but they should not be necessary for the entries to be displayed. (But it wouldn't hurt if you manage to make the upgrade of the Websocket work.)

> Uncaught (in promise) TypeError: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.

So to me this seems the most likely cause though I am not sure what exactly is going wrong.

**Comment by Gerardv514** [comment]
> Is it necessary to create WebSocket (as shown in Step 7 here: https://mariushosting.com/synology-install-vaultwarden-with-portainer/) ?

yes, I have this and no issues.

**Comment by BlackDex** [comment]
Also, try a different browser and private or incognito mode to see what that does.

**Comment by update-freak** [comment]
Tried it again with Firefox v130 (without plugins) on Win11 and got the same problem:

TypeError: SubtleCrypto.digest: Argument 2 could not be converted to any of: ArrayBufferView, ArrayBuffer.

What I also saw now is that after around 3min of loading circle I got 9 of 107 items on the list.
The other remaining items are not shown.
Also not the first 9 are shown, more a random pick of 9 items -> but this can be repeated and it's always these 9 items.

**Comment by Gerardv514** [comment]
Has this ever worked? And what has changed since last working?

**Comment by BlackDex** [comment]
It might be your reverse proxy or something else in between which is maybe caching or block or some Javascript.
It is not something we can fix on the server side i think.

Just be sure there is nothing cached or altered in between.
I do no know how Synology works in regards to all of this so not sure how to help there.

**Comment by update-freak** [comment]
Yes this worked.
Good questions what happened afterwards since its quite something time ago (I think at least 3 years). Whats changed: ADguard home, Unbound and other services added. DSM Updates etc. Don't know everything unfortunately.

I have to check what's the root cause:
dynv6, reverse proxy, adguard, Unbound etc.

So delete everything except the password-db and start with a clean container does not make sense right?

**Comment by mj084** [comment]
Try it without Adguard ;)

**Comment by update-freak** [comment]
- Adguard Home deactivated -> same result
- copied db -> same result
- I tried to change a item on the Android App -> deleted the app and logged in again -> saw the change -> sync works 
- yes from external the URL is reachable. The Problem occours after login

**Comment by Gerardv514** [comment]
I wouldn’t delete everything just yet, it would be beneficial to find what the root cause is. 

What you could do is copy your data folder into a new one and call it bwtest or whatever. Create a new container and same call it test. 

See if the problem is resolved. Also could try using the testing image. 

Another test would be to setup a clean test BW instance/container. Export data from existing (if you can using a client) and import into the clean test, what’s the result with that?

**Comment by mj084** [comment]
> * yes from external the URL is reachable. The Problem occours after login

So the problem still exists from external access with different browsers?

**Comment by update-freak** [comment]
I exported the items as json, created a clean new instance of the container and imported the json.
The result was that all items are displayed.
I also noticed while creating the new account that my previous passwort was not long enough -> not sure if this causes any problems.

But now it's fixed with export, clean new docker container and reimport

**Comment by Gerardv514** [comment]
But what made the issue break? What if this has a bigger consequence next time where it’s not recoverable at all.

**Comment by update-freak** [comment]
Thats the big question. For me it's not clear what caused this problem.
No, I did not have any attachments linked

**Comment by aheath70** [comment]
+1 with this issue. Apps on iPhone works, Google extension works, but no items are showing in my personal vault in the Webvault. I suspect it is definitely something in the actual vault, as I have 2 vaults. One works and displays everything, but my personal vault displays no items. 

If I extract the vault out to a JSON or CSV file, all the entries are there. 

It is nothing to do with the internet cache - problem still exists in Incognito window and across multiple computers and multiple browsers. I use Cloudflare tunnels, and the connection is not going through a local web proxy. If it was a proxy, then I would expect that all vaults I have would be experiencing the same issue, and they are not - one works, one doesn't.

**Comment by interunivers** [comment]
same issue for me. my personal vault laods very slowly but entries that are in an organisation dont load at all. I also cant export them from the webvault but the admin pannel still says the organization contains 78 entries. i also created a test organization which worked fine and i was able to creat entries in that. i am really a bit desperate no and really dont know where i should keep looking.

**Comment by BlackDex** [comment]
It must be an entry in the vault, possibly recently added via a new client maybe? 

Check the developer console of the browser to see if something useful is shown there.

**Comment by aheath70** [comment]
I get the following error in developer tools console - not sure if it is related or not.

```
encrypt-worker.0d0845fabb9cc329f366.js:1 Uncaught (in promise) TypeError: Failed to execute 'digest' on 'SubtleCrypto': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.
    at E.<anonymous> (encrypt-worker.0d0845fabb9cc329f366.js:1:16298)
    at Generator.next (<anonymous>)
    at encrypt-worker.0d0845fabb9cc329f366.js:1:14348
    at new Promise (<anonymous>)
    at x (encrypt-worker.0d0845fabb9cc329f366.js:1:14093)
    at E.hash (encrypt-worker.0d0845fabb9cc329f366.js:1:16093)
    at K.<anonymous> (encrypt-worker.0d0845fabb9cc329f366.js:1:28847)
    at Generator.next (<anonymous>)
    at encrypt-worker.0d0845fabb9cc329f366.js:1:25327
    at new Promise (<anonymous>)
```

**Comment by BlackDex** [comment]
@aheath70 which version of Vaultwarden are you using? Did you recently updated, if so, what was your previous version.

What happens in a new browser, one never used to visit the web-vault.

**Comment by interunivers** [comment]
> It must be an entry in the vault, possibly recently added via a new client maybe?
> 
> Check the developer console of the browser to see if something useful is shown there.

this is what the consol spits out as errors repeatedly and at the end just loads nothing

```
TypeError: SubtleCrypto.digest: Argument 2 could not be converted to any of: ArrayBufferView, ArrayBuffer. [web-crypto-function.service.ts:149:37](webpack://bitwarden/libs/common/src/platform/services/web-crypto-function.service.ts)
Starting decryption using multithreading [console-log.service.ts:43:16](webpack://bitwarden/libs/common/src/platform/services/console-log.service.ts)
TypeError: SubtleCrypto.digest: Argument 2 could not be converted to any of: ArrayBufferView, ArrayBuffer. [web-crypto-function.service.ts:149:37](webpack://bitwarden/libs/common/src/platform/services/web-crypto-function.service.ts)``
```

**Comment by BlackDex** [comment]
@interunivers, I'm afraid it will be very hard to tackle this. Maybe having the sync response will help me find what could be the issue. But I'm not sure. If you want then see my previous comment and the link there on how to extract that data if you want to share it with me.

**Comment by interunivers** [comment]
@BlackDex thank you for offering help. But which link are you reffering to?

**Comment by BlackDex** [comment]
Ah yes i just saw it was an other post haha. All those different items kinda similar but then not.

Here is the link:
https://github.com/dani-garcia/vaultwarden/issues/4870#issuecomment-2306749481

**Comment by interunivers** [comment]
@BlackDex I emailed the .har to you at hopefully the right email adress. It would interesset me very much if you can read something out of that. I hope the german parts aren't a problem.

**Comment by BlackDex** [comment]
@interunivers i have not yet received anything.
You sent it to the mail address in the image? starting with `security@`?
And ending in `vaultwarden.org`?

**Comment by BlackDex** [comment]
Ow, i have it now :) @dani-garcia  forwarded it to me.

**Comment by BlackDex** [comment]
@interunivers, I'm not really seeing why it would behave like this actually.
The requests and responses look the same on my server. The only difference i can see is that my server has compression enabled (gzip, brotli, zstd) and it looks like your reverse proxy is adding some headers which Vaultwarden already did.
Now i do not think that causes any issues, but it is probably better to let Vaultwarden handle most of these headers instead of the reverse proxy.

Since there are a lot of ciphers i also tried to detect something using some grep commands, but was not able to see anything which shouldn't be there in this form.

Might i suggest to try the following steps to see if you can pinpoint the specific issue.

1. Create a new user account with an empty vault.
2. Add a few ciphers to this account, and see if that causes an issue.
3. If not, then invite that user into the org you have, but just to one collection first, and i suggest to pick the smallest collection.
4. If that works without issues, then try to remove access to the collection granted at step 3, and grant it to an other collection, and continue these steps for all collections you have, but only one collection at a time.
5. If all above was also working, then one-by-one grant access to other collections and see what happens.

With the above, if all keeps working, without any issue, then it most likely is located in your personal vault, but then we have to figure out where and which item.

One way would be to export your personal vault, and import that into the new empty account (maybe first remove the test entries you created there). If then the test account still has no issues, we would need to compare both accounts sync output and see what the difference is there.

It's very strange this is causing an issue.
Also, i do wonder what happens if you revert to v1.32.0 and if that does solve all the issues or not?
That would be very strange though.

**Comment by interunivers** [comment]
@BlackDex Thank you for your efforts. 
Concerning the reverse proxy_headers, i already tried disabling them all (they are in place becasue nextcloud is runnig behind swag aswell) and it didn't change anything. And I might not have explained it but my personal vault is loading the only thing that isn't, is my organization that i use to share passwords with my family. And then the most annoying thing is i cant clone or export the items out of the organization because that feature only exists on the web. I'll try the downgrading if you could tell me how? Do i have have to modify the repository link slightly and if yes how?

**Comment by BlackDex** [comment]
I'm not sure where, but you probably have the text `latest` somewhere as a tag for Vaultwarden. If you change that to `1.32.0` it should be fixed to that version. I would recommend to create a backup first if you do not already have it. 

And, you could still try the collection steps i mentioned. 
If it is one specific collection, that also makes it easier for me to narrow it down maybe.

**Comment by aheath70** [comment]
> @aheath70 which version of Vaultwarden are you using? Did you recently updated, if so, what was your previous version.
> 
> What happens in a new browser, one never used to visit the web-vault.

I am running 1.32.0. I am a little nervous to update to the latest version, and it appears as though this is still happening for a few others on 1.32.1, so likely it is not version dependent and more likely an issue with an entry in the database somewhere.

No recent upgrades - this has been happening for a while. 

New browser window, new incognito window,, even different browser (tried Chrome and Edge) makes no difference. The issue persists regardless.

**Comment by interunivers** [comment]
@BlackDex There is a new interesseting behaviour, that my organisation doesnt send out invite emails. I could easily create a new user that work absolutley fine but the invitation email never arrives. I also tried the downgrading, that didnt change anything. Could it be that my sqllite is corrupt in some way?

**Comment by BlackDex** [comment]
If the sqlite is corrupt then more stuff would be strange i think.
You can check the sqlite database of course https://www.sqlite.org/pragma.html#pragma_integrity_check

I would also check the logs and maybe even enable debug logs. Because if you can invite someone into the org, the mail should just be sent. That is nothing to do with the web-vault not loading.
