### ISSUE TITLE
An error occured on iOS

### ISSUE THREAD

**Issue by imp1sh** [dani-garcia/vaultwarden#5016]
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.30.5
* Web-vault version: v2024.1.2b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.44.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, ADMIN_TOKEN, SMTP_HOST, SMTP_SSL, SMTP_PORT, SMTP_FROM, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*************",
  "domain_origin": "*****://*************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": false,
  "smtp_from": "********************",
  "smtp_from_name": "Vaultwarden - Password Tresor",
  "smtp_host": "**************",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "*********************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

### Vaultwarden Build Version

1.30.5

### Deployment method

Official Container Image

### Custom deployment method

Using Ansible to deploy as podman container

### Reverse Proxy

nginx 1.22.1

### Host/Server Operating System

Linux

### Operating System Version

Debian 12.7

### Clients

iOS

### Client Version

dunno how to find out on iOS (latest)

### Steps To Reproduce

1. Start iOS client
2. try to login with Master Password
3. An error occured

### Expected Result

Login should be possible

### Actual Result

An error occured message

### Logs

```text
reverse proxy logs:

my.domain.net-ssl_access.log:2001:4dd0:2aea:1b:d870:d487:1e4e:3ba0 - - [01/Oct/2024:12:43:35 +0200] "GET /api/devices/knowndevice HTTP/1.1" 200 5 "-" "Bitwarden_Mobile/2024.9.2 (iOS 17.6.1; Model iPhone)"
my.domain.net-ssl_access.log:2001:4dd0:2aea:1b:d870:d487:1e4e:3ba0 - - [01/Oct/2024:12:43:54 +0200] "POST /identity/accounts/prelogin HTTP/1.1" 200 72 "-" "Bitwarden_Mobile/2024.9.2 (iOS 17.6.1; Model iPhone)"

vaultwarden logs
[2024-10-01 10:43:35.233][request][INFO] GET /api/devices/knowndevice
[2024-10-01 10:43:35.233][response][INFO] (get_known_device) GET /api/devices/knowndevice => 200 OK
[2024-10-01 10:43:54.070][request][INFO] POST /identity/accounts/prelogin
[2024-10-01 10:43:54.070][response][INFO] (prelogin) POST /identity/accounts/prelogin => 200 OK
```

### Screenshots or Videos

![IMG_20241001_124135_2274](https://github.com/user-attachments/assets/d7b043f1-3743-4cd4-b440-b71718b31f92)

### Additional Context

The problem only seem to surface on iOS. Running Linux Desktop Bitwarden client and webgui no problem.

**Comment by tin607** [comment]
me too！

**Comment by BlackDex** [comment]
Try to update to the `testing` tagged version and let us know if that solves the issue. If so, that would mean we can release a new stable version soon and the issues are fixed.

**Comment by henningkessler** [comment]
Having the same issue after upgrading to Bitwarden mobil iOS version 2024.9.2 before it was fine...

**Comment by jakerobers** [comment]
I noticed the same issue. Using the `testing` tag fixed it for me. Thanks!
Also gave it a brief test by doing various CRUD operations through the iOS app and it feels stable.

**Comment by ErneX** [comment]
Hi, for those of us building from source, does the latest tag (1.32.0) solves this issue? Thanks in advance.

**Comment by NSenaud** [comment]
I can confirm it works for me on `testing` too 👍

**Comment by tim-hitchins-ekkosense** [comment]
1.32.0 works for me via proxmox helper scripts

**Comment by ErneX** [comment]
Just built 1.32.0 from source and the iOS issue is solved. Thank you all.

**Comment by imp1sh** [comment]
Looking forward to a new container release. Of course I don't want to stick with testing ^^

**Comment by zurie** [comment]
1.32. works for me on a self hosted nas with docker

**Comment by DeluxZ** [comment]
Running on latest also having this issue. Would be nice to have a new container release 👍🏼 Missing the ability of autofilling my passwords on my iPhone

**Comment by ooliver1** [comment]
1.32.0 works just fine after updating from 1.27 not working, 1.32 already has a release and has for a month

**Comment by BlackDex** [comment]
Closing this as it looks like it is fixed in testing and will be in the next stable release. Thanks for the info.

**Comment by Gerardv514** [comment]
> Try to update to the `testing` tagged version and let us know if that solves the issue. If so, that would mean we can release a new stable version soon and the issues are fixed.

Looking at their original version, this specific issue would have been resolved with latest rather than testing also. So It doesn’t appear  this issue part of any of the lingering issues that were left over from latest 1.32 to testing.

**Comment by BlackDex** [comment]
> > Try to update to the `testing` tagged version and let us know if that solves the issue. If so, that would mean we can release a new stable version soon and the issues are fixed.
> 
> Looking at their original version, this specific issue would have been resolved with latest rather than testing also. So It doesn’t appear this issue part of any of the lingering issues that were left over from latest 1.32 to testing.

You can't say that with certainty. There were some fixes in testing which have impact on syncing with the new clients. So for some latest would have been fine, where for others they needed testing.

**Comment by duckdalbe** [comment]
Just FYI, I'm running 1.32.0 (from the Archlinux package) and still have this problem.

**Comment by BlackDex** [comment]
That isn't using the `testing` branch, so it might as well not be fixed for you yet.

**Comment by GerryCrooked** [comment]
how would one use the testing branch without docker? im running it Vaultwarden currently on a dedicated LXC and am not too keen to move everything over to a docker instance

**Comment by BlackDex** [comment]
Just install the latest, as there was a new release just a few days ago

**Comment by uschumac** [comment]
I have installed 1.32.1 in Docker on my Synology NAS (DS 718+ with DSM 7.1.1-42962 Update 6) But still get the issue with bitwarden release 2024.9.2 on iphone 14 with ios 17.7. Is there something else, I have to do?

**Comment by BlackDex** [comment]
@uschumac you need to install the `testing` container version which has this fix.

Also, v1.32.2 is the current latest version which does **not** have the the fix for this issue.

**Comment by GerryCrooked** [comment]
> @uschumac you need to install the `testing` container version which has this fix.
> 
> Also, v1.32.2 is the current latest version which does **not** have the fix for this issue.

Does anyone know if the fix will be included in the next latest version?

**Comment by BlackDex** [comment]
@GerryCrooked All patches in the `main` branch will be in the `latest` version once released, which is always the case.
If you want to test and verify if this works, use the `testing` tagged container and report back.

**Comment by DeluxZ** [comment]
For me it's working again with the `testing` image and iOS 18.0

**Comment by uschumac** [comment]
@BlackDex Thank you for your quick response. I have installed vaultwarden/server -> testing from the repository in my Synology Docker. Unfortunately I still get errors the Username an Password is incorrect. With an iPad with iPadOS 18.01, with an iPhone with iOS 17.7, and a MacBook with MacOS Seqouia 15.01 
When looking at the protocol it says, that I have installed 1.32.2 645629a99.
Have I done something wrong?

**Comment by BlackDex** [comment]
If it says username/password incorrect that either means the username or password are incorrect, or the user does not exists.

Check the Vaultwarden Admin Backend `/admin` if the user(s) still exists.
If not, it might be that  you are not using the correct volume/storage anymore.
And i have no clue on how that works on a Synology.

**Comment by uschumac** [comment]
> If it says username/password incorrect that either means the username or password are incorrect, or the user does not exists.
> 
> Check the Vaultwarden Admin Backend `/admin` if the user(s) still exists. If not, it might be that you are not using the correct volume/storage anymore. And i have no clue on how that works on a Synology.

@BlackDex Thank you for the quiyk response again. My fault was a wrong entry in the Volumes section. It was docker/vaultwarden/data instead of docker/vaultwarden.

Thanks a lot, now it works again.
