### ISSUE TITLE
Error when adding new identifier : TypeError: Invalid version. Must be a string. Got type "undefined"

### ISSUE THREAD

**Issue by vbauchart** [dani-garcia/vaultwarden#6257]
### Prerequisites

- [x] I have searched the existing **Closed _AND_ Open** [Issues](https://github.com/dani-garcia/vaultwarden/issues?q=is%3Aissue%20) **_AND_** [Discussions](https://github.com/dani-garcia/vaultwarden/discussions?discussions_q=)
- [x] I have searched and read the [documentation](https://github.com/dani-garcia/vaultwarden/wiki/)

### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.34.3
* Web-vault version: v2025.7.0
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: SQLite
* Database version: 3.50.2
* Uses config.json: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://********************",
  "domain_origin": "*****://********************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.34.3

### Deployment method

Official Container Image

### Reverse Proxy

Traefik 3.5.1

### Host/Server Operating System

Linux

### Operating System Version

Arch Linux

### Clients

Browser Extension

### Client Version

Firefox 142.0.1 - 2025.8.1

### Steps To Reproduce

1. Through the Bitwarden Firefox extension, Create identifier
2. fill user and password
3. Save

If I add the same identifier with direct Web Interface, there is no error. I get the error only with Bitwarden Firefox extension.

### Expected Result

I expect the identifier to be stored.

### Actual Result

I get an Error : 

Async submit exception: TypeError: Invalid version. Must be a string. Got type "undefined".

### Logs

```text
no logs on server
```

### Additional Context

Javascript Console output : 

Async submit exception: TypeError: Invalid version. Must be a string. Got type "undefined". console-log.service.ts:51:17
    write console-log.service.ts:51
    error console-log.service.ts:28
    kl bit-submit.directive.ts:50
    o catchError.ts:117
    _error OperatorSubscriber.ts:79
    error Subscriber.ts:91
    g innerFrom.ts:94
    invoke zone.js:398
    onInvoke ng_zone.ts:473
    invoke zone.js:397
    run zone.js:113
    I zone.js:2537
    invokeTask zone.js:431
    onInvokeTask ng_zone.ts:450
    invokeTask zone.js:430
    runTask zone.js:161
    y zone.js:612
    invokeTask zone.js:519
    b zone.js:1141
    w zone.js:1172
    x zone.js:1205

**Comment by vbauchart** [comment]
I just realized my Traefik configuration was wrong since last major Vaultwarden version, I have to remove the websocket notifications endpoint

https://vaultwarden.discourse.group/t/note-breaking-change-in-upcoming-v1-31-0-stable-version/3051

PS: Thank you for the big work on Vaultwarden

**Comment by Studenthero** [comment]
I seem to be having the same problem, unable to edit and save in the Chome browser plugin. Could you tell me how I should solve this?

<img width="371" height="117" alt="Image" src="https://github.com/user-attachments/assets/7a88ea21-456c-4c26-898b-00e8d1df204d" />

**Comment by BlackDex** [comment]
> I seem to be having the same problem, unable to edit and save in the Chome browser plugin. Could you tell me how I should solve this?
> 
> <img alt="Image" width="371" height="117" src="https://private-user-images.githubusercontent.com/81549654/491186823-7a88ea21-456c-4c26-898b-00e8d1df204d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgyMjAzNzUsIm5iZiI6MTc1ODIyMDA3NSwicGF0aCI6Ii84MTU0OTY1NC80OTExODY4MjMtN2E4OGVhMjEtNDU2Yy00YzI2LTg5OGItMDBlOGQxZGYyMDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTE4VDE4Mjc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYmJkNzJkMGExYWQ3ODQ4MmU2M2Y5OGIzYjIyODIxOWU3MmNlYzU2ZmUxNmQ2Yzg5ZGE0MzIwYWM1ZWQ1ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vnN-JHwi8Ghf2eEUq9msvU4HGINGeFtp1mblw2p-2fA">

Make sure you are in the latest server and client version. If that doesn't solve it you would need to check the Vaultwarden logs
