### ISSUE TITLE
Editing issue in clients with 2025.12.0

### ISSUE THREAD

**Issue by ashoktvm** [dani-garcia/vaultwarden#6561]
### Prerequisites

- [x] I have searched the existing **Closed _AND_ Open** [Issues](https://github.com/dani-garcia/vaultwarden/issues?q=is%3Aissue%20) **_AND_** [Discussions](https://github.com/dani-garcia/vaultwarden/discussions?discussions_q=)
- [x] I have searched and read the [documentation](https://github.com/dani-garcia/vaultwarden/wiki/)

### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.34.3
* Web-vault version: v2025.7.0
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: SQLite
* Database version: 3.50.2
* Uses config.json: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* TZ environment: Asia/Kolkata
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: false
* HTTPS Check: false
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "****://*********",
  "domain_origin": "****://*********",
  "domain_path": "",
  "domain_set": false,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.34.3

### Deployment method

Official Container Image

### Reverse Proxy

pangolin 1.12.2

### Host/Server Operating System

Linux

### Clients

Desktop, Browser Extension

### Client Version

2025.12.0

### Steps To Reproduce

Steps To Reproduce
Login in bitwarden
Press edit into a login
Edit something (for example add a site)
Press Save
Get the error "An error has occurred"
Press Cancel
Check that the change was still made
Expected Result
The expectations is to get a success and that wasn't need to press the cancel.

Actual Result
An error has occurred, but with the change made.

Screenshots or Videos
No response

Additional Context
This issues only happens in version 2025.12, I test the 2025.11.2 and this don't happen.

Operating System
Windows

Operating System Version
Windows 11 Pro 25H2

Web Browser
Edge
Browser Version
Last stable available

Environment Versions
Version 2025.12.0
SDK 'main (0107af7)'
Shell 37.7.0
Renderer 138.0.7204.251
Node 22.20.0
Architecture x64

### Expected Result

It should say item saved

### Actual Result

It now says an error has occured

### Logs

```text

```

**Comment by mxsrm** [comment]
Use `:testing` tag until the new stable release is out.

**Comment by luisbandalap** [comment]
> Use `:testing` tag until the new stable release is out.

Be aware upgrading to :testing tag may logout all clients (mobile/desktop/browser). 

In the case of the android app i had to clear all app data and login again, not clearing app data makes the app throw `Unexpected push token received from bitwarden server: error decoding response body` error, 

With browser and desktop i had to login without clearing app data.

**Comment by ashoktvm** [comment]
> > Use `:testing` tag until the new stable release is out.
> 
> Be aware upgrading to :testing tag may logout all clients (mobile/desktop/browser).
> 
> In the case of the android app i had to clear all app data and login again, not clearing app data makes the app throw `Unexpected push token received from bitwarden server: error decoding response body` error,
> 
> With browser and desktop i had to login without clearing app data.

it just logged me out. No error other than that

**Comment by pvfpinto** [comment]
Hi,
When will go to stable?
Thanks.

**Comment by krombel** [comment]
The main change to fix this issue is implemented by https://github.com/dani-garcia/vaultwarden/pull/6557

=> I added this to my nginx configuration to fix this issue until stable is released:
```nginx
location = /api/tasks {
        return 200 '{"data":[],"object":"list"}';
}
```

**Comment by Misterbabou** [comment]
=> Until stable is released,  I added for Apache RP :
```apache
<Location /api/tasks>
  ErrorDocument 200 '{"data":[],"object":"list"}'
  Redirect 200 /
  Header always set Content-Type application/json
</Location>
```

**Comment by sammyke007** [comment]
Damn, I was going crazy and checking my config 10 times because of this. Glad to see it's not me 👍🏻

**Comment by deajan** [comment]
For completenees, here's what I use with Haproxy.
Of course one could add another acl to limit this fix to a certain host.
```
        # Vaultwarden 1.34.3 with Bitwarden CLI 2025.12 fix
        acl vaultwarden_fix             path_beg /api/tasks
        http-request return status 200 content-type "text/plain" lf-string '{"data":[],"object":"list"}' if vaultwarden_fix
```

**Comment by jpagh** [comment]
Caddy

```caddyfile
vaultwarden.example.com {
	route {
		@tasks path /api/tasks
		handle @tasks {
			header Content-Type application/json
			respond `{"data":[],"object":"list"}` 200
		}
		reverse_proxy /* vaultwarden:80 {
			header_up X-Real-IP {remote_host}
		}
		handle /* {
			abort
		}
	}
}
```

**Comment by manelrodero** [comment]
I've tried to figure out how to do this with Traefik. But it's a pure proxy and can't return content.

I should do something like this:

```
http:
  routers:
    vault:
      rule: "Host(`vault.mydomain.com`)"
      service: vault
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Router especial para el fix de /api/tasks
    vault-tasks:
      rule: "Host(`vault.mydomain.com`) && Path(`/api/tasks`)"
      service: vault-tasks
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    vault:
      loadBalancer:
        servers:
          - url: "http://10.10.10.100"

    # Servicio dummy que responde con el JSON vacío
    vault-tasks:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9999"

```

And then use a service with a simple nginx:alpine or similar to return empty JSON:

```
server {
    listen 80;
    location / {
        default_type application/json;
        return 200 '{"data":[],"object":"list"}';
    }
}
```

I'll wait for the official solution ;-)

**Comment by dwarf-king-hreidmar** [comment]
I ran into this issue (errors when saving passwords with the bitwarden plugin). I pulled the latest image (testing) and issues appear to have resolved. Thanks @dani-garcia and everyone else for the insanely quick fix.

**Comment by BlackDex** [comment]
This issue has been fixed already in `testing` via #6557, also some other PR's have been merged which solve some possible issues with the v2025.12 clients via #6574 and #6572.

Therefor I'm going to close this issues as it's already resolved.
We will try to release a new stable a.s.a.p.

**Comment by vincentization** [comment]
FYI I am still running into the Edit issue with the latest Chrome Browser Extension (Version 2025.12.1.)

iOS app seems to be not affected by this, however I can still not login there using the credentials (I guess this is unrelated, already reported in #6610 )

**Comment by BlackDex** [comment]
> FYI I am still running into the Edit issue with the latest Chrome Browser Extension (Version 2025.12.1.)
> 

That is a bit vague, what kind of issues, the same as the OP?
Did you checked you are on the latest Vaultwarden version?
A bit more details would be better, but first check the diagnostics.

> iOS app seems to be not affected by this, however I can still not login there using the credentials (I guess this is unrelated, already reported in [#6610](https://github.com/dani-garcia/vaultwarden/issues/6610) )

That issue is also already resolved by using an  updated version of Vaultwarden, so too me, that most likely says you are using an outdated version, but unable to say for sure, as you didn't posted those details.

**Comment by vincentization** [comment]
sorry for being vague, I am referring to the initial reported issue by OP. To me it sounded like only certain client versions were affected thats why I reported just that. However if you saying this issue is caused by an outdated **server** version, then I can ask our admin to perform an update and check if it fixes that. The current server version seems to be 2025.6.0.

in Regards to the iOS App issue: 
I can rule out an outdated client version, It was updated to 2026.1.0 before reporting. If this issue is also caused by server instead of client I will report back after the next update

**Comment by stefan0xC** [comment]
It's definitely outdated if it still reports 2025.6.0 because the newest version has been updated to report itself as 2025.12.0 already https://github.com/dani-garcia/vaultwarden/blob/feecfb20daeee7c61af84a904fb1bf40a8fa056f/src/api/core/mod.rs#L221

**Comment by vincentization** [comment]
the server update was just done (2025.12.0) and both issues are gone now. sorry for the misunderstanding and thanks a lot for your efforts in this project
